### ISSUE TITLE
Feature Request: blacklist sites

### ISSUE THREAD

**Issue by khuongduybui** [slaypni/MolyHaH#12]
There are a few sites with a dedicated keyboard-navigation design, such as gmail.com, superhuman.com, etc.
Is there any way to blacklist only these sites?

**Comment by slaypni** [comment]
There isn't. You could resort to `Disable entering HaH mode`.

**Comment by khuongduybui** [comment]
Got it, thanks. Do you think you can / should add a blacklist feature though?

**Comment by slaypni** [comment]
Not planned. Sometimes I also wish that feature, however the codebase is a bit old to update.

**Comment by khuongduybui** [comment]
Alright, sounds good. I can live with the Disable shortcut.
